name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  testing:
    runs-on: windows-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - run: MSBuild -ver
    - name: Run MSBuild
      run: msbuild -m ${{ github.workspace }}\lala\test.sln
